### ISSUE TITLE
regarding the number of classes in kitti_road data set

### ISSUE THREAD

**Issue by wenouyang** [Heych88/udacity-sdcnd-Semantic-Segmentation#1]
Hi, thanks for sharing the code. I have a question regarding the `kitti_road` data set, for some ground_truth images, we can find that there are some pixels marked with black color. I think kitti_road data set corresponds to a binary semantic segmentation problem, what does the black color represent here?

![capture](https://user-images.githubusercontent.com/5430158/32196095-7bfa12ca-bd8d-11e7-8296-58203ebe6d9e.JPG)

**Comment by Heych88** [comment]
Pink is road, red is unclassified and black is other roads such as intersections and other lanes of a split road.
